# Generated by Django 2.2.3 on 2021-10-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20211007_1551'),
    ]

    operations = [
    ]
