# Generated by Django 2.2.3 on 2021-10-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211007_1551'),
    ]

    operations = [
    ]
